apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - port: 80 # lan port
    targetPort: 80 # container port
    nodePort: 30080 # node port