apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-nginx
spec:
  template:
    metadata:
      annotations:
        checksum/index: {{ sha256sum(html/index.html) }}
      patchesStrategicMerge:
      - deployment-patch.yaml
