apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-nginx
  namespace: portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-nginx
  template:
    metadata:
      labels:
        app: portal-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: portal-html
            items:
              - key: index.html
                path: index.html
