apiVersion: v1
kind: Service
metadata:
  name: portal-nginx
  namespace: portal
spec:
  type: LoadBalancer   # 필요에 따라 NodePort / ClusterIP
  selector:
    app: portal-nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
