apiVersion: v1
kind: Service
metadata:
  name: portal-nginx
  namespace: portal
spec:
  type: NodePort
  selector:
    app: portal-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30081      # 예시 값 (LB에서 쓸 NodePort)
      protocol: TCP
